include:
 - project: "GNOME/citemplates"
   file: "templates/default-rules.yml"
 - component: gitlab.gnome.org/GNOME/citemplates/gnomeos-basic-ci@master
 - component: gitlab.gnome.org/GNOME/citemplates/release-service@master
   inputs:
     dist-job-name: "build-gnomeos"
